GET  https://fw-teaching.fi/demo/wdbocms/api/v1/products/ 

###

GET https://fw-teaching.fi/demo/wdbocms/api/v1/products/1002 
Content-Type: application/json

###

POST https://fw-teaching.fi/demo/wdbocms/api/v1/products/
Content-Type: application/json

{
    "name": "Hat (new one, better one)",
    "price": 20
}

### 

PUT https://fw-teaching.fi/demo/wdbocms/api/v1/products/1001
Content-Type: application/json

{
    "name": "skjorta",
    "price": 40
}

### 

DELETE https://fw-teaching.fi/demo/wdbocms/api/v1/products/1002



